[package]
name = "chinese-ZWCD"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.4", features = ["macros"] }  # Added macros feature
tower-sessions = "0.14.0"
axum-extra = { version = "0.10.1", features = ["cookie"] }
tokio = { version = "1", features = ["full"] }
diesel = { version = "2.1.0", features = ["sqlite", "r2d2", "chrono", "serde_json"] }
r2d2 = "0.8.10"
tera = "1.19.1"
serde = { version = "1.0.197", features = ["derive"] }
bcrypt = "0.17.0"
regex = "1.10.3"
lazy_static = "1.4.0"
dotenv = "0.15.0"
thiserror = "2.0.12"
serde_json = "1.0.114"
time = "0.3.34"
tower-http = { version = "0.6.4" , features = ["fs"]}
validator ={ version = "0.20.0", features = ["derive"] }
futures-util = "0.3.31"
unidecode = "0.3"
strsim = "0.10"
log = "0.4.27"
